/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.secondsemesterproject;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Items extends javax.swing.JFrame {

     
    /**
     * Creates new form ItemCard
     */
    
    Connection con;
    public Items() {
        initComponents();
       
           try {
               con = DriverManager.getConnection("jdbc:derby://localhost:1527/SecondSemesterProject","app","app");
           } catch (SQLException ex) {
               Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
           }
           ManageCateory.setVisible(false);
           ManageSupplier.setVisible(false);
           supplierfldmng.setVisible(false);
           categoryfldmng.setVisible(false);
           ADD.setVisible(false);
           DELETE.setVisible(false);
ADDINGcat.setVisible(false);
DeletingCat.setVisible(false);
        
  Codebtn.setEnabled(true);
  CategoryError.setVisible(false);
SupplierError.setVisible(false);
   this.setLocationRelativeTo(null);
   PopulateWithDatabaseSUP();
   PopulateWithDatabaseCAT();
   
   
        ManageCatLabel.setForeground(Color.WHITE);
        ManageSupLabel.setForeground(Color.WHITE);
        
        OnlyNumbersFirst.setVisible(false);
        OnlyNumbersFirst.setVisible(false);
         OnlyNumbersSecond.setVisible(false);
        OnlyNumbersSecond.setVisible(false);
    ProductNameError.setVisible(false);
        ConfirmButton.setEnabled(false);
    }
    
    String productName;
    int price;
    int price2;
    String supplier;
    String category;
int barcode;
      public Items(String productName, int price,int price2, String supplier, String category, int barcode) {
        this.productName = productName;
        this.price = price;
        this.price2 = price2;
        this.supplier = supplier;
        this.category = category;
        this.barcode = barcode;
    }
    
    
      public class Stock extends Items {
      
      private int quantity; 
      
      public int getQuantity (){
      
      return quantity;
      }
      
      }

    String user ;
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Category = new javax.swing.JComboBox<>();
        ProductName = new javax.swing.JTextField();
        SellingPrice = new javax.swing.JTextField();
        PriceBought = new javax.swing.JTextField();
        ConfirmButton = new javax.swing.JButton();
        Codebtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SupplierC = new javax.swing.JComboBox<>();
        Barcode = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ManageSupplier = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ManageCatLabel = new javax.swing.JLabel();
        ManageSupLabel = new javax.swing.JLabel();
        ADD = new javax.swing.JLabel();
        supplierfldmng = new javax.swing.JTextField();
        categoryfldmng = new javax.swing.JTextField();
        ADDINGcat = new javax.swing.JLabel();
        DELETE = new javax.swing.JLabel();
        DeletingCat = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ManageCateory = new javax.swing.JLabel();
        SupplierError = new javax.swing.JLabel();
        CategoryError = new javax.swing.JLabel();
        OnlyNumbersFirst = new javax.swing.JLabel();
        OnlyNumbersSecond = new javax.swing.JLabel();
        ProductNameError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(71, 6, 56));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Items Manager");

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\CP2\\Samm.png")); // NOI18N
        jLabel10.setText("jLabel1");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(51, 51, 51))))
        );

        ProductName.setForeground(new java.awt.Color(18, 30, 49));

        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        Codebtn.setText("Create A Code");
        Codebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodebtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Category");

        Barcode.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        Barcode.setForeground(new java.awt.Color(0, 0, 0));
        Barcode.setText("Click Create A Code to generate a code");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("TL");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("TL");

        ManageSupplier.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        ManageSupplier.setForeground(new java.awt.Color(0, 0, 0));
        ManageSupplier.setText("Supplier");

        jLabel14.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Product Name");

        jLabel15.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Selling Price");

        jLabel16.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Your Product Code");

        jLabel17.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Price Bought");

        jPanel3.setBackground(new java.awt.Color(71, 6, 56));

        ManageCatLabel.setBackground(new java.awt.Color(255, 255, 255));
        ManageCatLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        ManageCatLabel.setForeground(new java.awt.Color(255, 255, 255));
        ManageCatLabel.setText("Manage Category");
        ManageCatLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageCatLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageCatLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageCatLabelMouseExited(evt);
            }
        });

        ManageSupLabel.setBackground(new java.awt.Color(255, 255, 255));
        ManageSupLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        ManageSupLabel.setForeground(new java.awt.Color(255, 255, 255));
        ManageSupLabel.setText("Manage Supplier");
        ManageSupLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageSupLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageSupLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageSupLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ManageCatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManageSupLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(ManageCatLabel)
                .addGap(18, 18, 18)
                .addComponent(ManageSupLabel)
                .addContainerGap(316, Short.MAX_VALUE))
        );

        ADD.setBackground(new java.awt.Color(0, 0, 0));
        ADD.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        ADD.setForeground(new java.awt.Color(0, 0, 0));
        ADD.setText("ADD");
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDMouseExited(evt);
            }
        });
        ADD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ADDKeyPressed(evt);
            }
        });

        ADDINGcat.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        ADDINGcat.setForeground(new java.awt.Color(0, 0, 0));
        ADDINGcat.setText("ADD");
        ADDINGcat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDINGcatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDINGcatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDINGcatMouseExited(evt);
            }
        });

        DELETE.setBackground(new java.awt.Color(0, 0, 0));
        DELETE.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        DELETE.setForeground(new java.awt.Color(204, 0, 0));
        DELETE.setText("DELETE");
        DELETE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DELETEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DELETEMouseExited(evt);
            }
        });

        DeletingCat.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        DeletingCat.setForeground(new java.awt.Color(204, 0, 0));
        DeletingCat.setText("DELETE");
        DeletingCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletingCatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeletingCatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeletingCatMouseExited(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Supplier");

        ManageCateory.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        ManageCateory.setForeground(new java.awt.Color(0, 0, 0));
        ManageCateory.setText("Category");

        SupplierError.setBackground(new java.awt.Color(204, 0, 0));
        SupplierError.setForeground(new java.awt.Color(204, 0, 0));
        SupplierError.setText("Fill fields !");

        CategoryError.setForeground(new java.awt.Color(255, 0, 0));
        CategoryError.setText("Fill fields !");

        OnlyNumbersFirst.setBackground(new java.awt.Color(255, 0, 0));
        OnlyNumbersFirst.setForeground(new java.awt.Color(204, 0, 0));
        OnlyNumbersFirst.setText("ONLY NUMBERS! / EMPTY ERORR");

        OnlyNumbersSecond.setForeground(new java.awt.Color(204, 0, 0));
        OnlyNumbersSecond.setText("ONLY NUMBERS!/ EMPTY ERRO ");

        ProductNameError.setForeground(new java.awt.Color(204, 0, 0));
        ProductNameError.setText("This field is cumpolsery !!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Codebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addComponent(OnlyNumbersFirst))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(OnlyNumbersSecond)
                                                .addGap(3, 3, 3))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ManageSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ManageCateory, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CategoryError)
                                    .addComponent(SupplierError))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(PriceBought, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(118, 118, 118)
                                        .addComponent(jLabel16))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(categoryfldmng, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ADDINGcat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(DeletingCat))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(SupplierC, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Category, javax.swing.GroupLayout.Alignment.LEADING, 0, 170, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(56, 56, 56)
                                                .addComponent(ProductNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(47, 97, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(supplierfldmng, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ADD)
                                .addGap(76, 76, 76)
                                .addComponent(DELETE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(582, Short.MAX_VALUE)
                        .addComponent(Barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(SellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)
                                            .addComponent(OnlyNumbersFirst))
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(SupplierC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14)
                                            .addComponent(ProductNameError))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17)))
                                .addGap(16, 16, 16)
                                .addComponent(jLabel16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PriceBought, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(OnlyNumbersSecond))))
                        .addGap(18, 18, 18)
                        .addComponent(Barcode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Codebtn)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConfirmButton)
                            .addComponent(supplierfldmng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DELETE)
                            .addComponent(ManageSupplier)
                            .addComponent(SupplierError)
                            .addComponent(ADD))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoryfldmng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeletingCat)
                            .addComponent(ManageCateory)
                            .addComponent(CategoryError)
                            .addComponent(ADDINGcat))
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed

           
               /*jButton2.setEnabled(true);
               String productN = ProductName.getText();
               String supplier = jComboBox2.getSelectedItem().toString();
               int price = Integer.parseInt(PriceBought.getText());
               int price2 = Integer.parseInt(SellingPrice.getText());
               
               Items i = new Stock(productN, price, price2, supplier, productN);
               
               myAddedItems.add(i);*/
               
               
               
               
               String productName = ProductName.getText();
               int  price = Integer.parseInt(PriceBought.getText());
               int price2 = Integer.parseInt(SellingPrice.getText());
               String supplier = (String) SupplierC.getSelectedItem();
               String categoryl = (String) Category.getSelectedItem();
               
          
               
               
               int barcode = Integer.parseInt(Barcode.getText());
               
               Items newItem = new Items(productName, price,price2, supplier, category, barcode);
               //myAddedItems.add(newItem);
               //Manager m = new Manager();
               //m.SetItemListx(myAddedItems);
//Requester r = new Requester();
//r.SetItemList(myAddedItems);
String query = "INSERT INTO ITEMSINSYSTEM (ITEMCODE, ITEMNAME, BUYINGPRICE, SELLINGPRICE, SUPPLIER, CATEGORY) VALUES (?,?,?,?,?,?)";
try(PreparedStatement statement = con.prepareStatement(query)){



statement.setInt(1, barcode);
statement.setString(2, productName);
statement.setInt(3, price);
statement.setInt(4, price2);
statement.setString(5, supplier);
statement.setString(6, categoryl);


statement.executeUpdate();


JOptionPane.showMessageDialog(this, "Item Added to the system !");
// TODO add your handling code here:
           } catch (SQLException ex) {
               Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
           }
               
               

    }//GEN-LAST:event_ConfirmButtonActionPerformed

    
     private int getItemNumber(int categoryNumber) throws SQLException {
   int nextOrderNumber=0;
    String query = "SELECT MAX(ITEMCODE) AS maxitemcode FROM app.ITEMSINSYSTEM";
    PreparedStatement ps = con.prepareStatement(query);
    ResultSet rs = ps.executeQuery();
    if (rs.next()) {
        int maxOrderNumber = rs.getInt("maxitemcode");
        if (!rs.wasNull()) {
             nextOrderNumber = maxOrderNumber + 1;
        }
    }
    return nextOrderNumber;
}
    
    
    
    
    
    private void CodebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodebtnActionPerformed
boolean check = checkFields();
if (check) {
        
        int prNumber = 101;
        int prNumber2 = 202;
        int prNumber3 = 303;
        int NumberSet=0;
        
        
        
        
        if (Category.getSelectedItem().equals("Spices")) {
            try {
                NumberSet= getItemNumber(prNumber);
            } catch (SQLException ex) {
                Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
            }
            Barcode.setText(Integer.toString(NumberSet));
        
        } else if (Category.getSelectedItem().equals("Nuts")) {
         
            try {
                NumberSet= getItemNumber(prNumber2);
            } catch (SQLException ex) {
                Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
         Barcode.setText(Integer.toString(NumberSet));
        
        } else if (Category.getSelectedItem().equals("Gida")) {
            
            try {
                NumberSet= getItemNumber(prNumber3);
            } catch (SQLException ex) {
                Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
            }
            
         Barcode.setText(Integer.toString(NumberSet));
        
        }
        JOptionPane.showMessageDialog(this, "Code created ! "+ NumberSet + "Please confirm your addtion");
        ConfirmButton.setEnabled(true);
        
     
}
        // TODO add your handling code here:
    }//GEN-LAST:event_CodebtnActionPerformed

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void ManageCatLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageCatLabelMouseClicked

int i = JOptionPane.showConfirmDialog(this, "Are you sure you want to ADD/ DELETE a category in the system? ");
if (i==JOptionPane.YES_OPTION) {
  ManageCateory.setVisible(true);
categoryfldmng.setVisible(true);
ADDINGcat.setVisible(true);
DeletingCat.setVisible(true);

}

        // TODO add your handling code here:
    }//GEN-LAST:event_ManageCatLabelMouseClicked

    private void ManageSupLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageSupLabelMouseClicked

int i = JOptionPane.showConfirmDialog(this, "Are you sure you want to ADD/ DELETE a supplier in the system? ");
if (i==JOptionPane.YES_OPTION) {
  ManageSupplier.setVisible(true);
supplierfldmng.setVisible(true);
ADD.setVisible(true);
DELETE.setVisible(true);

}

        // TODO add your handling code here:
    }//GEN-LAST:event_ManageSupLabelMouseClicked

    public void PopulateWithDatabaseSUP() {
        String sql = "SELECT * FROM app.SUPPLIERS";
        try ( PreparedStatement p = con.prepareStatement(sql)) {

            ResultSet resultSet = p.executeQuery();
            while (resultSet.next()) {
               
                String NameOfSupplier = resultSet.getString("NAME");
                SupplierC.addItem(NameOfSupplier);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Store.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    
    public void PopulateWithDatabaseCAT() {
        String sql = "SELECT * FROM app.CATEGORIES";
        try ( PreparedStatement p = con.prepareStatement(sql)) {

            ResultSet resultSet = p.executeQuery();
            while (resultSet.next()) {
               
                String Categ = resultSet.getString("NAME");
                Category.addItem(Categ);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Store.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void ADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseClicked




String query = "INSERT INTO app.SUPPLIERS VALUES ? ";
String supplier = supplierfldmng.getText();
try(PreparedStatement statement = con.prepareStatement(query)){




statement.setString(1,supplier );


statement.executeUpdate();


JOptionPane.showMessageDialog(this, "Item Added to the system !");
SupplierC.addItem(supplier);
// TODO add your handling code here:
           } catch (SQLException ex) {
               Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
           }












        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMouseClicked

    private void DELETEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseClicked


String supplier = supplierfldmng.getText();
String query = "DELETE FROM app.SUPPLIERS WHERE NAME=  ? ";

try(PreparedStatement statement = con.prepareStatement(query)){




statement.setString(1,supplier );


statement.executeUpdate();


int i =JOptionPane.showConfirmDialog(this, "Supplier Deleted ! Do you want to delete also all items in system under this supplier ?");
if (i==JOptionPane.YES_OPTION) {

String sup = supplierfldmng.getText();
String query2 = "DELETE FROM app.ITEMSINSYSTEM WHERE SUPPLIER=  ? ";

try(PreparedStatement Thestatement = con.prepareStatement(query2)){




Thestatement.setString(1,sup );


Thestatement.executeUpdate();


JOptionPane.showMessageDialog(this, "Items With this supplier has been removed!");
SupplierC.removeItem(supplier);
// TODO add your handling code here:
           } catch (SQLException ex) {
               Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
           }



}else 
SupplierC.removeItem(supplier);
JOptionPane.showMessageDialog(this, "Supplier Deleted succesfully!");
// TODO add your handling code here:
           } catch (SQLException ex) {
               Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
           }



        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEMouseClicked

    private void ADDINGcatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDINGcatMouseClicked

        
   
      
      String query = "INSERT INTO CATEGORIES VALUES ? ";
String CAT = categoryfldmng.getText();
try(PreparedStatement statement = con.prepareStatement(query)){




statement.setString(1,CAT );


statement.executeUpdate();


JOptionPane.showMessageDialog(this, "Item Added to the system !");
Category.addItem(CAT);
// TODO add your handling code here:
           } catch (SQLException ex) {
               Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
           }

        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDINGcatMouseClicked

    
   
public boolean checkFields() {
    boolean checkPassed = true;
    String productName = ProductName.getText();
    String priceBought = PriceBought.getText();
    String priceSold = SellingPrice.getText();

    if (productName.isEmpty() || priceBought.isEmpty() || priceSold.isEmpty()) {
        // Handle empty fields
        ProductNameError.setVisible(productName.isEmpty());
        OnlyNumbersFirst.setVisible(priceSold.isEmpty() || Integer.parseInt(priceSold) == 0);
        OnlyNumbersSecond.setVisible(priceBought.isEmpty() || Integer.parseInt(priceBought) == 0);
        checkPassed = false;
    } else {
        try {
            int parsedPriceBought = Integer.parseInt(priceBought);
            int parsedPriceSold = Integer.parseInt(priceSold);

            // Check for conditions
            if (parsedPriceBought == 0) {
                OnlyNumbersFirst.setVisible(true);
                checkPassed = false;
            }
            if (parsedPriceSold == 0) {
                OnlyNumbersSecond.setVisible(true);
                checkPassed = false;
            }
            if (containsNumber(productName)) {
                ProductNameError.setVisible(true);
                checkPassed = false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter appropriate values to the fields");
            checkPassed = false;
        }
    }
    
    return checkPassed;
}

private boolean containsNumber(String str) {
    for (char c : str.toCharArray()) {
        if (Character.isDigit(c)) {
            return true;
        }
    }
    return false;
}

    
    
    
    private void DeletingCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletingCatMouseClicked

String CAT = categoryfldmng.getText();
String query = "DELETE FROM CATEGORIES WHERE NAME=  ? ";

try(PreparedStatement statement = con.prepareStatement(query)){




statement.setString(1,CAT );


statement.executeUpdate();


JOptionPane.showMessageDialog(this, "Item Deleted to the system !");
Category.removeItem(supplier);
// TODO add your handling code here:
           } catch (SQLException ex) {
               Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
           }

JOptionPane.showMessageDialog(this, "Supplier Deleted succesfully!");

        // TODO add your handling code here:
    }//GEN-LAST:event_DeletingCatMouseClicked

    private void ADDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ADDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDKeyPressed

    private void ManageCatLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageCatLabelMouseEntered
        // TODO add your handling code here:
        
        
        ManageCatLabel.setForeground(new Color(121,158,81));

    }//GEN-LAST:event_ManageCatLabelMouseEntered

    private void ManageCatLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageCatLabelMouseExited
        // TODO add your handling code here:
        
        ManageCatLabel.setForeground(Color.WHITE);

    }//GEN-LAST:event_ManageCatLabelMouseExited

    private void ManageSupLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageSupLabelMouseEntered
        // TODO add your handling code here:
        ManageSupLabel.setForeground(new Color(121,158,81));
        
        
    }//GEN-LAST:event_ManageSupLabelMouseEntered

    private void ManageSupLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageSupLabelMouseExited
        // TODO add your handling code here:
        
        ManageSupLabel.setForeground(Color.WHITE);
        
        
    }//GEN-LAST:event_ManageSupLabelMouseExited

    private void ADDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseEntered

ADD.setForeground(Color.RED);

        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMouseEntered

    private void ADDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseExited

ADD.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMouseExited

    private void ADDINGcatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDINGcatMouseEntered

ADDINGcat.setForeground(Color.RED);
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDINGcatMouseEntered

    private void DeletingCatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletingCatMouseExited

        DeletingCat.setForeground(Color.RED);

        // TODO add your handling code here:
    }//GEN-LAST:event_DeletingCatMouseExited

    private void ADDINGcatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDINGcatMouseExited
ADDINGcat.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_ADDINGcatMouseExited

    private void DELETEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseEntered
DELETE.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEMouseEntered

    private void DELETEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseExited

DELETE.setForeground(Color.RED);
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEMouseExited

    private void DeletingCatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletingCatMouseEntered
DeletingCat.setForeground(Color.BLACK);
            
        // TODO add your handling code here:
    }//GEN-LAST:event_DeletingCatMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Items s = new Items();
                s.setVisible(true);
                
                  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADD;
    private javax.swing.JLabel ADDINGcat;
    private javax.swing.JLabel Barcode;
    private javax.swing.JComboBox<String> Category;
    private javax.swing.JLabel CategoryError;
    private javax.swing.JButton Codebtn;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JLabel DELETE;
    private javax.swing.JLabel DeletingCat;
    private javax.swing.JLabel ManageCatLabel;
    private javax.swing.JLabel ManageCateory;
    private javax.swing.JLabel ManageSupLabel;
    private javax.swing.JLabel ManageSupplier;
    private javax.swing.JLabel OnlyNumbersFirst;
    private javax.swing.JLabel OnlyNumbersSecond;
    private javax.swing.JTextField PriceBought;
    private javax.swing.JTextField ProductName;
    private javax.swing.JLabel ProductNameError;
    private javax.swing.JTextField SellingPrice;
    private javax.swing.JComboBox<String> SupplierC;
    private javax.swing.JLabel SupplierError;
    private javax.swing.JTextField categoryfldmng;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField supplierfldmng;
    // End of variables declaration//GEN-END:variables
}
