/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.secondsemesterproject;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.regex.Pattern;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
      jPanel2.hide();
        
      EmailsDONT.setVisible(false);
      MobDont.setVisible(false);
      PasswordDONT.setVisible(false);
      FLDSness.setVisible(false);
      CorrectChError.setVisible(false);
      IncorrectFormatEML.setVisible(false);
    this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        UserNameFLDSnIn = new javax.swing.JTextField();
        PasswordFldSnIn = new javax.swing.JTextField();
        LoginBtn = new javax.swing.JLabel();
        GoCreateAcnt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CorrectChError = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Mobile = new javax.swing.JTextField();
        CreateNameFld = new javax.swing.JTextField();
        ConfirmEmaily = new javax.swing.JTextField();
        PasswordFLD2 = new javax.swing.JTextField();
        PasswordFLD = new javax.swing.JTextField();
        CreateEmlFld = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        EmailsDONT = new javax.swing.JLabel();
        MobDont = new javax.swing.JLabel();
        PasswordDONT = new javax.swing.JLabel();
        LoginAlreadyHave = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        UserNAMEchosen = new javax.swing.JTextField();
        IncorrectFormatEML = new javax.swing.JLabel();
        FLDSness = new javax.swing.JLabel();
        managercheckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel12.setBackground(new java.awt.Color(71, 6, 56));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Picture1Log.png")); // NOI18N
        jLabel23.setText("jLabel1");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("The Golden Nuts Company  ");

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 23)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Stock Management System");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(269, 269, 269))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Sign in | Manager | Employee System");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Name");

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Password");

        UserNameFLDSnIn.setBackground(new java.awt.Color(255, 255, 255));
        UserNameFLDSnIn.setForeground(new java.awt.Color(71, 6, 56));
        UserNameFLDSnIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 6, 56), 3, true));

        PasswordFldSnIn.setBackground(new java.awt.Color(255, 255, 255));
        PasswordFldSnIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 6, 56), 3));

        LoginBtn.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 24)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(0, 0, 0));
        LoginBtn.setText("Login ");
        LoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginBtnMouseExited(evt);
            }
        });

        GoCreateAcnt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        GoCreateAcnt.setForeground(new java.awt.Color(0, 0, 0));
        GoCreateAcnt.setText("No account ? Create a new account now !");
        GoCreateAcnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoCreateAcntMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GoCreateAcntMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GoCreateAcntMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UserNameFLDSnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GoCreateAcnt)
                                    .addComponent(PasswordFldSnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 263, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(234, 234, 234))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNameFLDSnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordFldSnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LoginBtn)
                .addGap(29, 29, 29)
                .addComponent(GoCreateAcnt)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(71, 6, 56));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Create A New Account");

        CorrectChError.setText("Please enter correct characters !");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(316, 316, 316))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(CorrectChError, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CorrectChError)
                .addGap(14, 14, 14))
        );

        jLabel6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Name");

        jLabel7.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Create A Password");

        jLabel8.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Confirm Email");

        jLabel9.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Mobile Phone");

        jLabel10.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Email");

        jLabel11.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Confirm Password");

        Mobile.setBackground(new java.awt.Color(255, 255, 255));
        Mobile.setForeground(new java.awt.Color(71, 6, 56));
        Mobile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 6, 56), 3, true));

        CreateNameFld.setBackground(new java.awt.Color(255, 255, 255));
        CreateNameFld.setForeground(new java.awt.Color(71, 6, 56));
        CreateNameFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 6, 56), 3, true));

        ConfirmEmaily.setBackground(new java.awt.Color(255, 255, 255));
        ConfirmEmaily.setForeground(new java.awt.Color(71, 6, 56));
        ConfirmEmaily.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 6, 56), 3, true));

        PasswordFLD2.setBackground(new java.awt.Color(255, 255, 255));
        PasswordFLD2.setForeground(new java.awt.Color(71, 6, 56));
        PasswordFLD2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 6, 56), 3, true));

        PasswordFLD.setBackground(new java.awt.Color(255, 255, 255));
        PasswordFLD.setForeground(new java.awt.Color(71, 6, 56));
        PasswordFLD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 6, 56), 3, true));

        CreateEmlFld.setBackground(new java.awt.Color(255, 255, 255));
        CreateEmlFld.setForeground(new java.awt.Color(71, 6, 56));
        CreateEmlFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 6, 56), 3, true));

        jLabel12.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Create Account !");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        EmailsDONT.setForeground(new java.awt.Color(204, 0, 0));
        EmailsDONT.setText("Emails Don't Match");

        MobDont.setForeground(new java.awt.Color(204, 0, 0));
        MobDont.setText("Enter A Valid Number");

        PasswordDONT.setBackground(new java.awt.Color(204, 0, 0));
        PasswordDONT.setForeground(new java.awt.Color(204, 0, 0));
        PasswordDONT.setText("Passwords Don't Match");

        LoginAlreadyHave.setBackground(new java.awt.Color(0, 0, 0));
        LoginAlreadyHave.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        LoginAlreadyHave.setForeground(new java.awt.Color(0, 0, 0));
        LoginAlreadyHave.setText("Already Have An Account ? | Login");
        LoginAlreadyHave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginAlreadyHaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginAlreadyHaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginAlreadyHaveMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Create A User Name");

        UserNAMEchosen.setBackground(new java.awt.Color(255, 255, 255));
        UserNAMEchosen.setForeground(new java.awt.Color(71, 6, 56));
        UserNAMEchosen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 6, 56), 3, true));

        IncorrectFormatEML.setForeground(new java.awt.Color(204, 0, 0));
        IncorrectFormatEML.setText("Incorrect Emaıl Format");

        FLDSness.setForeground(new java.awt.Color(204, 0, 0));
        FLDSness.setText("ALL FIELDS ARE NECESSERY !!");

        managercheckbox.setText("I am a manager");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(UserNAMEchosen, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(CreateNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LoginAlreadyHave, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ConfirmEmaily, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PasswordFLD, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CreateEmlFld, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MobDont)
                                    .addComponent(PasswordDONT, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmailsDONT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IncorrectFormatEML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(PasswordFLD2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(managercheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(109, 109, 109))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(FLDSness, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(33, 740, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FLDSness)
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CreateNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginAlreadyHave))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateEmlFld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(IncorrectFormatEML))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmEmaily, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(EmailsDONT))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(MobDont))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordDONT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PasswordFLD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PasswordFLD2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(managercheckbox)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNAMEchosen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -41, 880, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoCreateAcntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoCreateAcntMouseClicked

jTabbedPane1.setSelectedIndex(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_GoCreateAcntMouseClicked

    public boolean checkFields() {
    boolean checkPassed = true;
   String name = CreateNameFld.getText();
        String email = CreateEmlFld.getText();
        String emaily = ConfirmEmaily.getText();
        String mob = Mobile.getText();
        String password = PasswordFLD.getText();
        String confPassword = PasswordFLD2.getText();

    if (name.isEmpty() ||emaily.isEmpty() || mob.isEmpty()|| password.isEmpty()|| confPassword.isEmpty()) {
        FLDSness.setVisible(true);
        checkPassed = false;
    } else {
        try {
            
          
            if (containsNumber(name)) {
                CorrectChError.setVisible(true);
                checkPassed = false;
            }
            else if (!Pattern.matches("\\w+@\\w+\\.\\w+", email)) {
            IncorrectFormatEML.setVisible(true);
                
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter appropriate values to the fields");
            checkPassed = false;
        }
    }
    
    return checkPassed;
}

private boolean containsNumber(String str) {
    for (char c : str.toCharArray()) {
        if (Character.isDigit(c)) {
            return true;
        }
    }
    return false;
}
    

    
    
private boolean checker() {
    boolean matches = false;
    String emailEntered = CreateEmlFld.getText();
    String confirmEmail = ConfirmEmaily.getText();
    String password = PasswordFLD.getText();
    String conPass = PasswordFLD2.getText();
    String mobStr = Mobile.getText();
    
    // Check if the email and confirm email match
    if (!emailEntered.equals(confirmEmail)) {
        EmailsDONT.setVisible(true);
    }
    // Check if the password and confirm password match
    else if (!password.equals(conPass)) {
        PasswordDONT.setVisible(true);
    }
    // Check if the email format is valid
    else if (!emailEntered.matches("\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b")) {
        EmailsDONT.setVisible(true);
    }
    // Check if the mobile is valid (contains only digits)
    else if (mobStr.isEmpty() || !mobStr.matches("\\d+")) {
        MobDont.setVisible(true);
    }
    // All checks passed
    else {
        System.out.println("Checker Method Passed!");
        matches = true;
    }
    
    return matches;
}
    
    
    
 
     
    
     
    
    
    
    
    
    
    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
if (checkFields()) {
        
       
        
        

if (checker()) {
   EmailsDONT.setVisible(false);
      MobDont.setVisible(false);
      PasswordDONT.setVisible(false);
      FLDSness.setVisible(false);
      CorrectChError.setVisible(false);
      IncorrectFormatEML.setVisible(false);

createAnAccount();
} else {

JOptionPane.showMessageDialog(this, "Error creating your account ! Please check your enter information again.");
}
        
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    
    public void createAnAccount() {
    
     String USERname = UserNAMEchosen.getText();
        String name = CreateNameFld.getText();
        String password = new String(PasswordFLD.getText());
    int mobile =Integer.parseInt(Mobile.getText());
    String email = CreateEmlFld.getText();
        boolean isManager = managercheckbox.isSelected();
          if (usernameExists(USERname)) {
            JOptionPane.showMessageDialog(null, "Username already exists. Please choose a different username.");
            return; // Exit the method without creating the account
        
          
          }else {
          
          saveUserInfoToFile(USERname, name, mobile, password, isManager);
          JOptionPane.showMessageDialog(this, "done");
          }
          
          
    
        
        
    
    
    
    }
    
    
    private void saveUserInfoToFile(String username, String name, int mobile,String password, boolean isManager) {
        try {
           
            
            // Append the user's information to the file
            BufferedWriter writer = new BufferedWriter(new FileWriter("C:\\Users\\User\\Desktop\\CP2\\users.txt", true));
            writer.write(username + "," + name + "," + mobile + "," + password + "," + isManager);
            writer.newLine();
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    
    public boolean isLoginValid(String username, String password) {
        boolean loginvalid= false;
        try {
            File file = new File("C:\\Users\\User\\Desktop\\CP2\\users.txt");
            Scanner scanner = new Scanner(file);
            
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                String[] parts = line.split(",");
                
                if (parts.length >= 5 && parts[0].equals(username) && parts[3].equals(password) && Boolean.parseBoolean(parts[4])) {
                  loginvalid= true;
                  
                   Manager m = new Manager();
                  
                    m.setVisible(true);
                    dispose();
                   
                  break; 
                  
                   
                } else if (parts.length >= 5 && parts[0].equals(username) && parts[3].equals(password) && !Boolean.parseBoolean(parts[4])) {
                loginvalid= true;
                    WelV1 w = new WelV1();
                    w.setVisible(true);
                    dispose();
                    
                    break;
                }  
              
               
            }
             if (!loginvalid) {
               JOptionPane.showMessageDialog(this, "wronginfo");
                   
               }
            scanner.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        
       return loginvalid;
    }
    
    
     private boolean usernameExists(String username) {
        try {
            File file = new File("C:\\Users\\User\\Desktop\\CP2\\users.txt");
            BufferedReader reader = new BufferedReader(new FileReader(file));

            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length >= 1 && parts[0].equals(username)) {
                    reader.close();
                    return true; // Username exists
                }
            }
             reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
          return false;
     }
        
    
    private void LoginAlreadyHaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginAlreadyHaveMouseClicked

jTabbedPane1.setSelectedIndex(0);


        // TODO add your handling code here:
    }//GEN-LAST:event_LoginAlreadyHaveMouseClicked

    private void LoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseClicked

isLoginValid(UserNameFLDSnIn.getText(), PasswordFldSnIn.getText());


       




        // TODO add your handling code here:
    }//GEN-LAST:event_LoginBtnMouseClicked

    private void GoCreateAcntMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoCreateAcntMouseEntered
GoCreateAcnt.setForeground(Color.RED);

        // TODO add your handling code here:
    }//GEN-LAST:event_GoCreateAcntMouseEntered

    private void GoCreateAcntMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoCreateAcntMouseExited
      
GoCreateAcnt.setForeground(Color.BLACK);        
// TODO add your handling code here:
    }//GEN-LAST:event_GoCreateAcntMouseExited

    private void LoginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseEntered

LoginBtn.setForeground(Color.RED);
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginBtnMouseEntered

    private void LoginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseExited

LoginBtn.setForeground(Color.BLACK);   
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginBtnMouseExited

    private void LoginAlreadyHaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginAlreadyHaveMouseEntered

LoginAlreadyHave.setForeground(Color.red);

        // TODO add your handling code here:
    }//GEN-LAST:event_LoginAlreadyHaveMouseEntered

    private void LoginAlreadyHaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginAlreadyHaveMouseExited
LoginAlreadyHave.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_LoginAlreadyHaveMouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered

        
jLabel12.setForeground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited

jLabel12.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 LoginPage p = new LoginPage();
                p.setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConfirmEmaily;
    private javax.swing.JLabel CorrectChError;
    private javax.swing.JTextField CreateEmlFld;
    private javax.swing.JTextField CreateNameFld;
    private javax.swing.JLabel EmailsDONT;
    private javax.swing.JLabel FLDSness;
    private javax.swing.JLabel GoCreateAcnt;
    private javax.swing.JLabel IncorrectFormatEML;
    private javax.swing.JLabel LoginAlreadyHave;
    private javax.swing.JLabel LoginBtn;
    private javax.swing.JLabel MobDont;
    private javax.swing.JTextField Mobile;
    private javax.swing.JLabel PasswordDONT;
    private javax.swing.JTextField PasswordFLD;
    private javax.swing.JTextField PasswordFLD2;
    private javax.swing.JTextField PasswordFldSnIn;
    private javax.swing.JTextField UserNAMEchosen;
    private javax.swing.JTextField UserNameFLDSnIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox managercheckbox;
    // End of variables declaration//GEN-END:variables
}
