/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.secondsemesterproject;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    
      Connection con;
    public Manager() {
        initComponents();
        PopulateDashboard();
        
         try {
               con = DriverManager.getConnection("jdbc:derby://localhost:1527/SecondSemesterProject","app","app");
           } catch (SQLException ex) {
               Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
           }
         
          this.setLocationRelativeTo(null);
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        GoTOItemsM = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GoToStockM = new javax.swing.JLabel();
        GoTORequestsM = new javax.swing.JLabel();
        GoTOCustomersM = new javax.swing.JLabel();
        GoToOrdersM = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        StockLabel = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        ITlabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        CustLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        TotalLable = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        OutLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        RequestedLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        LowStock = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        REFRESHbtn = new javax.swing.JButton();
        DetailedInfoWindow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(71, 6, 56));

        GoTOItemsM.setBackground(new java.awt.Color(255, 255, 255));
        GoTOItemsM.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        GoTOItemsM.setForeground(new java.awt.Color(255, 255, 255));
        GoTOItemsM.setText("Items");
        GoTOItemsM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoTOItemsMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GoTOItemsMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GoTOItemsMMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\CP2\\Samm.png")); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        GoToStockM.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        GoToStockM.setForeground(new java.awt.Color(255, 255, 255));
        GoToStockM.setText("Products In Stock");
        GoToStockM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoToStockMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GoToStockMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GoToStockMMouseExited(evt);
            }
        });

        GoTORequestsM.setBackground(new java.awt.Color(255, 255, 255));
        GoTORequestsM.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        GoTORequestsM.setForeground(new java.awt.Color(255, 255, 255));
        GoTORequestsM.setText("View Requests");
        GoTORequestsM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoTORequestsMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GoTORequestsMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GoTORequestsMMouseExited(evt);
            }
        });

        GoTOCustomersM.setBackground(new java.awt.Color(255, 255, 255));
        GoTOCustomersM.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        GoTOCustomersM.setForeground(new java.awt.Color(255, 255, 255));
        GoTOCustomersM.setText("Customers");
        GoTOCustomersM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoTOCustomersMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GoTOCustomersMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GoTOCustomersMMouseExited(evt);
            }
        });

        GoToOrdersM.setBackground(new java.awt.Color(255, 255, 255));
        GoToOrdersM.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        GoToOrdersM.setForeground(new java.awt.Color(255, 255, 255));
        GoToOrdersM.setText("Orders ");
        GoToOrdersM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoToOrdersMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GoToOrdersMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GoToOrdersMMouseExited(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon("C:/Users/User/Desktop/CP2/icons8-request-30.png")); // NOI18N
        jLabel20.setText("jLabel20");

        jLabel21.setIcon(new javax.swing.ImageIcon("C:/Users/User/Desktop/CP2/icons8-contact-30.png")); // NOI18N
        jLabel21.setText("jLabel20");

        jLabel23.setIcon(new javax.swing.ImageIcon("C:/Users/User/Desktop/CP2/icons8-products-30.png")); // NOI18N
        jLabel23.setText("jLabel20");

        jLabel29.setIcon(new javax.swing.ImageIcon("C:/Users/User/Desktop/CP2/icons8-create-order-30.png")); // NOI18N
        jLabel29.setText("jLabel20");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(GoTOItemsM)
                .addGap(51, 51, 51)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GoToStockM)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GoTORequestsM)
                .addGap(52, 52, 52)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GoToOrdersM)
                .addGap(55, 55, 55)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GoTOCustomersM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GoTORequestsM)
                            .addComponent(jLabel20)
                            .addComponent(GoToOrdersM)
                            .addComponent(jLabel29)
                            .addComponent(GoTOCustomersM)
                            .addComponent(jLabel21)
                            .addComponent(GoToStockM)
                            .addComponent(jLabel23))
                        .addGap(48, 48, 48))))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GoTOItemsM)
                .addGap(52, 52, 52))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel19.setBackground(new java.awt.Color(71, 6, 56));
        jLabel19.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(71, 6, 56));
        jLabel19.setText("Stock");

        StockLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        StockLabel.setForeground(new java.awt.Color(121, 158, 81));
        StockLabel.setText("0");

        jLabel31.setIcon(new javax.swing.ImageIcon("C:/Users/User/Desktop/CP2/Overall.png")); // NOI18N
        jLabel31.setText("jLabel20");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(StockLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StockLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel30.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(71, 6, 56));
        jLabel30.setText("Total Products In System");

        ITlabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        ITlabel.setForeground(new java.awt.Color(71, 6, 56));
        ITlabel.setText("0");

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\CP2\\productsL.png")); // NOI18N
        jLabel13.setText("jLabel4");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ITlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ITlabel)
                    .addComponent(jLabel13)))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel28.setBackground(new java.awt.Color(71, 6, 56));
        jLabel28.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(71, 6, 56));
        jLabel28.setText("Number Of Customers");

        CustLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CustLabel.setForeground(new java.awt.Color(0, 0, 0));
        CustLabel.setText("0");

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\CP2\\customers.png")); // NOI18N
        jLabel11.setText("jLabel4");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(CustLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel28))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustLabel)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel27.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(71, 6, 56));
        jLabel27.setText("Total Orders");

        TotalLable.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TotalLable.setForeground(new java.awt.Color(71, 6, 56));
        TotalLable.setText("0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TotalLable, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalLable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel32.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("Out Of Stock Products ");

        OutLabel.setBackground(new java.awt.Color(0, 0, 0));
        OutLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        OutLabel.setForeground(new java.awt.Color(255, 0, 0));
        OutLabel.setText("0");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\CP2\\outofstock.png")); // NOI18N
        jLabel7.setText("jLabel4");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel32))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(OutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)))
        );

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel39.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 0, 0));
        jLabel39.setText("Requested Products ");

        RequestedLabel.setBackground(new java.awt.Color(0, 0, 0));
        RequestedLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        RequestedLabel.setForeground(new java.awt.Color(255, 0, 0));
        RequestedLabel.setText("0");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(RequestedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addGap(50, 50, 50))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RequestedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel26.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(71, 6, 56));
        jLabel26.setText("Low Stock ");

        LowStock.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        LowStock.setForeground(new java.awt.Color(121, 158, 81));
        LowStock.setText("0");

        jLabel34.setIcon(new javax.swing.ImageIcon("C:/Users/User/Desktop/CP2/icons8-low-priority-50.png")); // NOI18N
        jLabel34.setText("jLabel20");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel26))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(LowStock, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel34)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LowStock)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 45)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Manager Dashboard");

        REFRESHbtn.setText("REFRESH");
        REFRESHbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REFRESHbtnActionPerformed(evt);
            }
        });

        DetailedInfoWindow.setText("Details");
        DetailedInfoWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailedInfoWindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4)
                        .addGap(129, 129, 129)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DetailedInfoWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(REFRESHbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DetailedInfoWindow)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jPanel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(REFRESHbtn)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel4)))
                        .addContainerGap(35, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void GoTOItemsMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoTOItemsMMouseClicked
        
        Items i = new Items();
        i.setVisible(true);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_GoTOItemsMMouseClicked

    
    public void PopulateDashboard() {
    
     String sqlQueryForOrders = "SELECT * FROM app.Orders";
     
     String sqlQueryForStock = "SELECT * FROM app.ITEMSINSTOCK";
    
     String sqlQueryForItems = "SELECT * FROM app.ITEMSINSYSTEM";
     String sqlQueryForCustomers = "SELECT * FROM app.Customers";
     String sqlQueryForRequests = "SELECT * FROM app.REQUESTS";
      String query = "SELECT * FROM ITEMSINSTOCK WHERE QUANTITYAVALIABLE < 10";
     String query2 = "SELECT * FROM ITEMSINSTOCK WHERE QUANTITYAVALIABLE = 0";
      int countOfOrders =0;
      int countOfStock =0;
      int countOfItems =0;
      int countOfCustomers =0;
      int outOfStock = 0;
      int lowStock = 0;
      int requests = 0;
    try {
               con = DriverManager.getConnection("jdbc:derby://localhost:1527/SecondSemesterProject", "app", "app");
             Statement stmt = con.createStatement();
             Statement stmt2 = con.createStatement();
             Statement stmt3= con.createStatement();
             Statement stmt4 = con.createStatement();
             Statement stmt5 = con.createStatement();
             Statement stmt6 = con.createStatement();
             Statement stmt7 = con.createStatement();
             ResultSet rs = stmt.executeQuery(sqlQueryForOrders);
             ResultSet rs2 = stmt2.executeQuery(sqlQueryForItems);
             ResultSet rs3 = stmt3.executeQuery(sqlQueryForStock);
 ResultSet rs4 = stmt4.executeQuery(sqlQueryForCustomers);
 ResultSet rs5 = stmt5.executeQuery(query);
ResultSet rs6 = stmt6.executeQuery(query2);
ResultSet rs7 = stmt7.executeQuery(sqlQueryForRequests);
            while (rs.next()) {
              
             countOfOrders++;
            } while (rs2.next()) {
             countOfStock++;
            } while (rs3.next()) {
             countOfItems++;
            }
            while (rs4.next()) { 
            countOfCustomers++;
            }
            while (rs5.next()) {
             lowStock++;
            }
            while (rs6.next()) {
             outOfStock++;
            
            }
            while(rs7.next()) {
            requests++;
            }
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
  StockLabel.setText(Integer.toString(countOfStock));
     ITlabel.setText(Integer.toString(countOfItems));
      CustLabel.setText(Integer.toString(countOfCustomers));
         OutLabel.setText(Integer.toString(outOfStock));
         TotalLable.setText(Integer.toString(countOfOrders));
      LowStock.setText(Integer.toString(lowStock));
      RequestedLabel.setText(Integer.toString(requests));
    
    }
        
   
    


    
    private void GoTOItemsMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoTOItemsMMouseEntered

        GoTOItemsM.setForeground(new Color(121,158,81));
        // TODO add your handling code here:
    }//GEN-LAST:event_GoTOItemsMMouseEntered

    private void GoTOItemsMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoTOItemsMMouseExited

        GoTOItemsM.setForeground(Color.WHITE);

        // TODO add your handling code here:
    }//GEN-LAST:event_GoTOItemsMMouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void GoToStockMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoToStockMMouseClicked

        
        Store b = new Store();

        b.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_GoToStockMMouseClicked

    private void GoToStockMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoToStockMMouseEntered
        GoToStockM.setForeground(new Color(121,158,81));

        // TODO add your handling code here:
    }//GEN-LAST:event_GoToStockMMouseEntered

    private void GoToStockMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoToStockMMouseExited

        GoToStockM.setForeground(Color.WHITE);

        // TODO add your handling code here:
    }//GEN-LAST:event_GoToStockMMouseExited

    private void GoTORequestsMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoTORequestsMMouseClicked

RequestsVIEWER v = new RequestsVIEWER();
        v.setVisible(true);
     

        // TODO add your handling code here:
    }//GEN-LAST:event_GoTORequestsMMouseClicked

    private void GoTORequestsMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoTORequestsMMouseEntered

        GoTORequestsM.setForeground(new Color(121,158,81));

        // TODO add your handling code here:
    }//GEN-LAST:event_GoTORequestsMMouseEntered

    private void GoTORequestsMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoTORequestsMMouseExited
        GoTORequestsM.setForeground(Color.WHITE);
    }//GEN-LAST:event_GoTORequestsMMouseExited

    private void GoTOCustomersMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoTOCustomersMMouseEntered
        GoTOCustomersM.setForeground(new Color(121,158,81));

        // TODO add your handling code here:
    }//GEN-LAST:event_GoTOCustomersMMouseEntered

    private void GoTOCustomersMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoTOCustomersMMouseExited

        GoTOCustomersM.setForeground(Color.WHITE);

        // TODO add your handling code here:
    }//GEN-LAST:event_GoTOCustomersMMouseExited

    private void GoToOrdersMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoToOrdersMMouseClicked

        
        Order o = new Order();
        
      
        o.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_GoToOrdersMMouseClicked

    private void GoToOrdersMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoToOrdersMMouseEntered
        GoToOrdersM.setForeground(new Color(121,158,81));

        // TODO add your handling code here:
    }//GEN-LAST:event_GoToOrdersMMouseEntered

    private void GoToOrdersMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoToOrdersMMouseExited
        GoToOrdersM.setForeground(Color.WHITE);
    }//GEN-LAST:event_GoToOrdersMMouseExited

    private void GoTOCustomersMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoTOCustomersMMouseClicked

Customers s = new Customers();
s.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_GoTOCustomersMMouseClicked

    private void REFRESHbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REFRESHbtnActionPerformed

PopulateDashboard();
        // TODO add your handling code here:
    }//GEN-LAST:event_REFRESHbtnActionPerformed

    private void DetailedInfoWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailedInfoWindowActionPerformed

        DetailedSystemInfo i = new DetailedSystemInfo();
        i.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_DetailedInfoWindowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustLabel;
    private javax.swing.JButton DetailedInfoWindow;
    private javax.swing.JLabel GoTOCustomersM;
    private javax.swing.JLabel GoTOItemsM;
    private javax.swing.JLabel GoTORequestsM;
    private javax.swing.JLabel GoToOrdersM;
    private javax.swing.JLabel GoToStockM;
    private javax.swing.JLabel ITlabel;
    private javax.swing.JLabel LowStock;
    private javax.swing.JLabel OutLabel;
    private javax.swing.JButton REFRESHbtn;
    private javax.swing.JLabel RequestedLabel;
    private javax.swing.JLabel StockLabel;
    private javax.swing.JLabel TotalLable;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
