/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.secondsemesterproject;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class RequestsVIEWER extends javax.swing.JFrame {

    
     DefaultTableModel myOrdersTable = new DefaultTableModel();
     
      String cols[] = {"Product Name" , "Quantity Wanted"};
      
    /**
     * Creates new form RequestsVIEWER
     * 
     * 
     * 
     */
    
     Connection con;
    
    
    
    public void PopulateWithDatabase() {
        String sql = "SELECT * FROM REQUESTS";
        try ( PreparedStatement p = con.prepareStatement(sql)) {

            ResultSet resultSet = p.executeQuery();
            while (resultSet.next()) {
                int quantity = resultSet.getInt("QUANTITY");
                String ProductName = resultSet.getString("PRODUCTNAME");
                
 myOrdersTable.addRow(new Object[]{ProductName, quantity});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Store.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    
     private void deleteProductFromRequests(Object productName) {
        String mySQL = "DELETE * FROM REQUESTS WHERE PRODUCTNAME = ?";
        try {
            PreparedStatement statement = con.prepareStatement(mySQL); 
            
            statement.setObject(1, productName);
            statement.executeUpdate();
            
            
        }catch (SQLException ex) {
            
        } 

     }
    
    
    public RequestsVIEWER() {
    
        
        initComponents();
        
         try {
               con = DriverManager.getConnection("jdbc:derby://localhost:1527/SecondSemesterProject","app","app");
           } catch (SQLException ex) {
               Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
           }
     AvlblRequestsTbl.setModel(myOrdersTable);
        myOrdersTable.setColumnIdentifiers(cols);
        
         this.setLocationRelativeTo(null);
        PopulateWithDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AvlblRequestsTbl = new javax.swing.JTable();
        DeleteRequestBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(71, 6, 56));

        jLabel15.setBackground(new java.awt.Color(222, 222, 222));
        jLabel15.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Requests Avaliable");

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\CP2\\Samm.png")); // NOI18N
        jLabel16.setText("jLabel1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(144, 144, 144)))
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel9)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(26, 26, 26))
        );

        AvlblRequestsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(AvlblRequestsTbl);

        DeleteRequestBtn.setBackground(new java.awt.Color(222, 222, 222));
        DeleteRequestBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        DeleteRequestBtn.setForeground(new java.awt.Color(0, 0, 0));
        DeleteRequestBtn.setText("Delete Selected Request ");
        DeleteRequestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteRequestBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteRequestBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteRequestBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(DeleteRequestBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(DeleteRequestBtn)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteRequestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteRequestBtnMouseClicked
   int selectedRow =AvlblRequestsTbl.getSelectedRow();
                
                if (selectedRow == -1) {
                    JOptionPane.showMessageDialog(null, "Please select a product to delete.");
                    return;
                }
                
               int i = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this request form the system? ", "Loggin Out", JOptionPane.YES_NO_OPTION);
        if (i==JOptionPane.YES_OPTION) {
        
   
                Object productName =  AvlblRequestsTbl.getValueAt(selectedRow, 1);
                deleteProductFromRequests(productName);
                myOrdersTable.removeRow(selectedRow);
        }

                


        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteRequestBtnMouseClicked

    private void DeleteRequestBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteRequestBtnMouseEntered


DeleteRequestBtn.setForeground(Color.red);

        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteRequestBtnMouseEntered

    private void DeleteRequestBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteRequestBtnMouseExited

DeleteRequestBtn.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteRequestBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestsVIEWER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestsVIEWER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestsVIEWER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestsVIEWER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestsVIEWER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AvlblRequestsTbl;
    private javax.swing.JLabel DeleteRequestBtn;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
